version: 2.1
jobs:
  build:
    steps:
      - tag_new_commit
      - run:
          name: Add tag to commit
          command: |
            git config --global user.email "winorbita@gmail.com"
            git config --global user.name "WinterOrbit"
            git remote set-url origin https://winorbit:$GITHUB_PASS@github.com/Winorbit/web_ui.git
            CURRENT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
            DATETIME_NOW=$(date +"%Y-%m-%d-%H-%M")
            git tag -a "${CURRENT_BRANCH_NAME}.${DATETIME_NOW}" -m "comment"
            git push -u origin $CURRENT_BRANCH_NAME --follow-tags
